pipeline {
    agent any
    stages {
        stage('Setup') {
            steps {
                sh "bash jenkins/setup.sh"
            }
        }
        // stage('Test') {
        //     steps {
        //         //
        //     }
        // }
        // stage('Craete Schema') {
        //     steps {
        //         //
        //     }
        // }
        // stage('Craete Schema') {
        //     steps {
        //         //
        //     }
        // }
    }
}